services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./data/node_modules:/app/node_modules
      - ./data/.next:/app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
